#!/bin/bash
#
# cyhy-runner   This shell script takes care of starting and stopping
#               cyhy-runner.
#
# chkconfig: 2345 80 30
# description: cyhy-runner
# processname: cyhy-runner
# pidfile: /var/run/cyhy-runner.pid

### BEGIN INIT INFO
# Provides: cyhy-runner
# Required-Start: $local_fs $network cloud-final
# Required-Stop: $local_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop cyhy-runner
# Description: cyhy-runner
### END INIT INFO

# We want this service to be started very late in the boot process.
# This is because cloud-init may have to format the cyhy-runner data
# volume, and that can take some time.
#
# Including cloud-final in Required-Start above should ensure that
# cloud-init is finished running before this service is started.

# Source function library.
. /etc/rc.d/init.d/functions

prog="cyhy-runner"

start() {
    # Start daemon
    ret=0
    echo -n $"Starting $prog: "
    /usr/local/bin/cyhy-runner /var/cyhy/runner &
    echo $! > /var/run/cyhy-runner.pid
    RETVAL=$?
    echo

    [ $RETVAL -eq 0 ] && return 0 || return 1
}

stop() {
    # Stop daemon
    echo -n $"Shutting down $prog: "
    killproc cyhy-runner
    RETVAL=$?
    echo
    return $RETVAL
}

status -p /var/run/cyhy-runner.pid > /dev/null
running=$?

# See how we were called.
case "$1" in
    start)
	[ $running -eq 0 ] && exit 0
	start
	RETVAL=$?
	;;
    stop)
	[ $running -eq 0 ] || exit 0
	stop
	RETVAL=$?
	;;
    restart)
	stop
	start
	RETVAL=$?
	;;
    status)
	echo -n cyhy-runner; status -p /var/run/cyhy-runner.pid -l cyhy-runner
	RETVAL=$?
	;;
    *)
	echo $"Usage: $0 {start|stop|restart|status}"
	RETVAL=2
esac

exit $RETVAL
