#!/bin/sh

before=false
after=true
# We need the sed script because the file redirection doesn't play
# nice with find's exec clause below.  See, for example, here:
# https://stackoverflow.com/questions/15030563/redirecting-stdout-with-find-exec-and-without-creating-new-shell
sed_script=scripts/toggle_prevent_destroy_sed_command.sh

while getopts ":htf" opt
do
    case ${opt} in
        h)
            echo "Usage:"
            echo "    toggle_prevent_destroy -h        Display this help message."
            echo "    toggle_prevent_destroy -t        Set prevent_destroy true everywhere."
            echo "    toggle_prevent_destroy -f        Set prevent_destroy false everywhere."
            exit 0
            ;;
        f)
            before=true
            after=false
            ;;
        \?)
            echo "Invalid option: -$OPTARG" 1>&2
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

regex="s/\(prevent_destroy[[:space:]]*=[[:space:]]*\)$before/\1$after/g"
tmp_file=$(mktemp)
find . -maxdepth 1 -name "*.tf" -exec $sed_script $regex {} $tmp_file \;

# Cleanup
rm $tmp_file
