---
# Each entry in this file is a label that will be applied to pull requests
# if there is a match based on the matching rules for the entry. Please see
# the actions/labeler documentation for more information:
# https://github.com/actions/labeler#match-object
ansible:
  - changed-files:
      - any-glob-to-any-file:
          - ansible/**
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
github-actions:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/**
packer:
  - changed-files:
      - any-glob-to-any-file:
          - packer/**
python:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.py"
terraform:
  - changed-files:
      - any-glob-to-any-file:
          - terraform/**
upstream update:
  - head-branch:
      - lineage/skeleton
version bump:
  - changed-files:
      - any-glob-to-any-file:
          - version.txt
