---
- hosts: cyhy_commander,cyhy_dashboard,cyhy_reporter,nessus
  name: Create the directory used for cyhy-commander, cyhy-core, and Nessus credentials
  become: yes
  become_method: ansible.builtin.sudo
  tasks:
    - name: Create the /etc/cyhy directory
      ansible.builtin.file:
        group: "{{ cyhy_user_username }}"
        mode: 0750
        owner: "{{ cyhy_user_username }}"
        path: /etc/cyhy
        state: directory
  vars_files:
    - vars/cyhy_user.yml
