---
- name: Install and configure cyhy-commander
  hosts: cyhy_commander
  become: true
  become_method: ansible.builtin.sudo
  roles:
    - role: cyhy_commander
      vars:
        cyhy_commander_maxmind_license_key: "{{ maxmind_license_key }}"
  vars_files:
    - vars/maxmind_license_key.yml
