---
- hosts: cyhy_archive
  name: Install cyhy-archive helper script
  become: yes
  become_method: ansible.builtin.sudo
  roles:
    - role: cyhy_archive
      vars:
        cyhy_archive_maxmind_license_key: "{{ maxmind_license_key }}"
  vars_files:
    - vars/maxmind_license_key.yml
