---
- name: Install and configure cyhy-commander
  hosts: cyhy_commander
  become: true
  become_method: ansible.builtin.sudo
  roles:
    - role: cyhy_commander
      vars:
        cyhy_commander_install_geoipupdate: true
        cyhy_commander_maxmind_account_id: "{{ maxmind_account_id }}"
        cyhy_commander_maxmind_license_key: "{{ maxmind_license_key }}"
  vars_files:
    - vars/maxmind_information.yml
