---
- hosts: cyhy_reporter
  name: Install and configure cyhy-reports
  become: yes
  become_method: ansible.builtin.sudo
  roles:
    - xfs
    - cyhy_reports
    - cyhy_mailer
  vars:
    texmf_buffer_size: 100000000
    texmf_main_memory: 10000000
  vars_files:
    - vars/maxmind_license_key.yml
