---
- hosts: cyhy_reporter
  name: Install and configure cyhy-reports
  become: yes
  become_method: ansible.builtin.sudo
  roles:
    - xfs
    - role: cyhy_reports
      vars:
        cyhy_reports_maxmind_license_key: "{{ maxmind_license_key }}"
    - cyhy_mailer
  vars:
    texmf_buffer_size: 100000000
    texmf_main_memory: 10000000
  vars_files:
    - vars/maxmind_license_key.yml
