---
- name: Install cyhy-archive helper script
  hosts: cyhy_archive
  become: yes
  become_method: ansible.builtin.sudo
  roles:
    - role: cyhy_archive
      vars:
        cyhy_archive_maxmind_account_id: "{{ maxmind_account_id }}"
        cyhy_archive_maxmind_license_key: "{{ maxmind_license_key }}"
  vars_files:
    - vars/maxmind_information.yml
