---
- name: Install and configure cyhy-reports
  hosts: cyhy_reporter
  become: true
  become_method: ansible.builtin.sudo
  roles:
    - xfs
    - role: cyhy_reports
      vars:
        cyhy_reports_maxmind_account_id: "{{ maxmind_account_id_secret }}"
        cyhy_reports_maxmind_license_key: "{{ maxmind_license_key_secret }}"
        cyhy_reports_texmf_buffer_size: 100000000
        cyhy_reports_texmf_main_memory: 10000000
    - cyhy_mailer
  tasks:
    # This Docker image is used to communicate with the serverless
    # Valkey ElastiCache resource in the BOD VPC.  We cannot install
    # valkey-tools on the CyHy reporter instance directly because it
    # is still using Debian Buster, which does not offer this package.
    - name: Pull official valkey Docker image
      community.general.docker_image:
        name: valkey/valkey:alpine
        source: pull
