---
- name: Install and configure cyhy-reports
  hosts: cyhy_reporter
  become: true
  become_method: ansible.builtin.sudo
  roles:
    - xfs
    - role: cyhy_reports
      vars:
        cyhy_reports_maxmind_account_id: "{{ maxmind_account_id }}"
        cyhy_reports_maxmind_license_key: "{{ maxmind_license_key }}"
        cyhy_reports_texmf_buffer_size: 100000000
        cyhy_reports_texmf_main_memory: 10000000
    - cyhy_mailer
  vars_files:
    - vars/maxmind_information.yml
