---
- name: Install and configure Nessus
  hosts: nessus
  become: true
  become_method: ansible.builtin.sudo
  roles:
    - role: cyhy_runner
      vars:
        cyhy_runner_file_owner_group: "{{ cyhy_user_username }}"
        cyhy_runner_file_owner_username: "{{ cyhy_user_username }}"
    - role: nessus
      vars:
        nessus_package_bucket: ncats-3rd-party-packages
        nessus_version: 10.5.1
    - more_ephemeral_ports
