---
- name: Upgrade the base image, set up Debian Backports, and configure apt over HTTPS
  hosts: all
  become: yes
  become_method: ansible.builtin.sudo
  tasks:
    - name: Upgrade system packages
      ansible.builtin.include_role:
        name: upgrade

    - name: Set up Debian Backports repository
      ansible.builtin.include_role:
        name: backports

    - name: Set up apt to use HTTPS
      ansible.builtin.include_role:
        name: apt_over_https
