---
- name: Configure host for BOD 20-01 VDP scanning
  hosts: vdp_scan
  become: true
  become_method: ansible.builtin.sudo
  roles:
    - role: vdp_scanner
      vars:
        vdp_scanner_file_owner_group: "{{ cyhy_user_username }}"
        vdp_scanner_file_owner_username: "{{ cyhy_user_username }}"
