---
# tasks file for orchestrator

#
# orchestrator secrets
#
- name: Create the secrets directory
  ansible.builtin.file:
    path: /var/cyhy/orchestrator/secrets
    group: cyhy
    mode: 0755
    owner: cyhy
    state: directory

- name: Create files with MongoDB credentials
  ansible.builtin.template:
    dest: "/var/cyhy/orchestrator/secrets/{{ item.filename }}"
    group: cyhy
    mode: 0440
    owner: cyhy
    src: mongodb_credentials.yml.j2
  loop:
    # reporter
    - database: "{{ reporter_db }}"
      filename: cyhy_read_creds.yml
      username: "{{ reporter_user }}"
      password: "{{ reporter_pw }}"
    # scan-reader
    - database: "{{ scan_reader_db }}"
      filename: scan_read_creds.yml
      username: "{{ scan_reader_user }}"
      password: "{{ scan_reader_pw }}"
    # scan-writer
    - database: "{{ scan_writer_db }}"
      filename: scan_write_creds.yml
      username: "{{ scan_writer_user }}"
      password: "{{ scan_writer_pw }}"
  loop_control:
    label: "{{ item.filename }}"


- name: Create the AWS config
  ansible.builtin.template:
    dest: /var/cyhy/orchestrator/secrets/aws_config
    group: cyhy
    mode: 0440
    owner: cyhy
    src: aws_config.j2

#
# Create a cron job for scanning
#
- name: Create the cron job
  when: production_workspace|bool
  block:
    - name: Add /usr/local/bin to cron's path
      ansible.builtin.cron:
        env: yes
        name: PATH
        user: cyhy
        value: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

    # This cron job runs at midnight UTC on Saturday mornings, so it
    # should be done by 2PM on Saturday.
    - name: Create a cron job for BOD 18-01 scanning
      ansible.builtin.cron:
        hour: '0'
        job: cd /var/cyhy/orchestrator && docker compose up -d 2>&1 | /usr/bin/logger -t orchestrator
        minute: '0'
        name: "BOD 18-01 scanning"
        user: cyhy
        weekday: '6'
