---
# The master key for all reports
cyhy_reporter_master_report_key: "{{ lookup('aws_ssm', '/cyhy/master_report_key') }}"

# commander mongo username
cyhy_reporter_commander_user: "{{ lookup('aws_ssm', '/cyhy/mongo/users/commander/user') }}"
# commander mongo password
cyhy_reporter_commander_pw: "{{ lookup('aws_ssm', '/cyhy/mongo/users/commander/password') }}"
# commander mongo database
cyhy_reporter_commander_db: "{{ lookup('aws_ssm', '/cyhy/mongo/users/commander/database') }}"

# scan-reader mongo username
cyhy_reporter_scan_reader_user: "{{ lookup('aws_ssm', '/cyhy/mongo/users/scan-reader/user') }}"
# scan-reader mongo password
cyhy_reporter_scan_reader_pw: "{{ lookup('aws_ssm', '/cyhy/mongo/users/scan-reader/password') }}"
# scan-reader mongo database
cyhy_reporter_scan_reader_db: "{{ lookup('aws_ssm', '/cyhy/mongo/users/scan-reader/database') }}"

# The development users
cyhy_reporter_dev_users: "{{ lookup('aws_ssm', '/cyhy/dev/users').split(',') }}"
