---
# defaults file for cyhy_commander

# The maximum number of jobs to assign to each nessus host (vulnscanner).
# This value is used in the "production" section of the cyhy-commander
# configuration file this role generates.
jobs_per_nessus_host: 16

# The maximum number of jobs to assign to each nmap host (portscanner).
# This value is used in the "production" section of the cyhy-commander
# configuration file this role generates.
jobs_per_nmap_host: 8

# The maximum number of hosts that are scheduled to have scanning restarted
# whose next scan stage should be updated per cyhy-commander cycle. The checks
# for hosts that were "up" or "down" are processed separately so the total
# number of hosts that are transitioned is double the provided value. Hosts
# that are "up" are transitioned to PORTSCAN and hosts that are "down" are
# transitioned to NETSCAN1.
# This value is used in the "production" section of the cyhy-commander
# configuration file this role generates.
next_scan_limit: 8192
