---
#
# code_gov_update secrets
#
- name: Create the secrets directory
  ansible.builtin.file:
    group: "{{ code_gov_update_group }}"
    mode: u=rwx,g=rx,o=rx
    owner: "{{ code_gov_update_user }}"
    path: /var/cyhy/code-gov-update/secrets
    state: directory

- name: Create the llnl-scraper config
  ansible.builtin.template:
    dest: /var/cyhy/code-gov-update/secrets/scraper.json
    group: "{{ code_gov_update_group }}"
    mode: u=r,g=r,o=
    owner: "{{ code_gov_update_user }}"
    src: scraper.json.j2

- name: Create the AWS config
  ansible.builtin.template:
    dest: /var/cyhy/code-gov-update/secrets/aws_config
    group: "{{ code_gov_update_group }}"
    mode: u=r,g=r,o=
    owner: "{{ code_gov_update_user }}"
    src: aws_config.j2

#
# Create a cron job
#
- name: Create the cron job
  when: production_workspace|bool
  block:
    - name: Add /usr/local/bin to cron's path
      ansible.builtin.cron:
        env: true
        name: PATH
        user: "{{ code_gov_update_user }}"
        value: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

    # This cron job runs at midnight UTC on Friday mornings
    - name: Create a cron job for updating the code.gov JSON
      ansible.builtin.cron:
        hour: "0"
        job: >-
          cd /var/cyhy/code-gov-update
          && docker compose up --detach 2>&1
          | /usr/bin/logger --tag code-gov-update
        minute: "0"
        name: code.gov update
        user: "{{ code_gov_update_user }}"
        weekday: "5"
