---
dependencies: []
galaxy_info:
  author: VM Fusion Dev
  company: CISA Cyber Assessments
  description: Set up the requirements for the cisagov/client-cert-update Docker image
  galaxy_tags: []
  license: CC0
  # Our standalone Ansible roles require this Ansible version
  min_ansible_version: "2.10"
  namespace: cyhy
  platforms:
    - name: Debian
      versions:
        - bookworm
  role_name: client_cert_update
