---
#
# Create the mgmt_ops user
#
- name: Create the mgmt_ops user
  ansible.builtin.user:
    name: mgmt_ops

# Make sure the /home/mgmt_ops/.ssh directory exists
- name: Create the /home/mgmt_ops/.ssh directory
  ansible.builtin.file:
    group: mgmt_ops
    mode: 0700
    owner: mgmt_ops
    path: /home/mgmt_ops/.ssh
    state: directory

#
# Create the .ssh/authorized_keys file for mgmt_ops
#
- name: Create .ssh/authorized_keys file for mgmt_ops
  ansible.builtin.lineinfile:
    create: yes
    group: mgmt_ops
    line: "{{ lookup('aws_ssm', '/ssh/public_keys/' + item) }}"
    mode: 0600
    owner: mgmt_ops
    path: /home/mgmt_ops/.ssh/authorized_keys
  loop: "{{ ops_users }}"
