---
# Grab the existing users and groups
- name: Grab the existing users
  ansible.builtin.getent:
    database: passwd
    fail_key: no
- name: Grab the existing groups
  ansible.builtin.getent:
    database: group
    fail_key: no


#
# Add the cyhy user to the docker group, if they both exist
#
- name: Add the cyhy user to the docker group
  ansible.builtin.user:
    append: yes
    groups: docker
    name: cyhy
  when: (getent_passwd.cyhy is defined) and (getent_group.docker is defined)


#
# Add dev known users to the cyhy and docker groups, if they exist
#
- name: Add dev users to the cyhy group
  ansible.builtin.user:
    append: yes
    groups: cyhy
    name: "{{ item }}"
  loop: "{{ dev_users }}"
  when: getent_group.cyhy is defined

- name: Add dev users to the docker group
  ansible.builtin.user:
    append: yes
    groups: docker
    name: "{{ item }}"
  loop: "{{ dev_users }}"
  when: getent_group.docker is defined
